### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by ivanzhang92** [luxiaojian/resume#1]
期望职位：Web前端实习生，~~NodeJ~~Node.js服务端实习生

**Comment by ivanzhang92** [comment]
加油

**Comment by luxiaojian** [comment]
收到，已修改，谢谢！

**Comment by ivanzhang92** [comment]
建议：
- 本科/~~南京信息工程大学计算机与软件学院计算机科学与技术专业~~南京信息工程大学计算机科学与技术
- ～～期望城市：杭州，上海，南京～～
- 多火工作室技术~~群殴~~分享：用node.js实现一个简单的个人博客程序（简历正规一些）
- 多火工作室技术~~群殴~~分享：正则表达式（简历正规一些）
- 大二下到大三期间担任学校计算机社团多火工作室社长 ~~（大学期间最开心日子）~~（简历不是博客，正规一些）

笔误：
前端工具：Bower/Gulp/~~SaSS~~Sass（建议）/~~Yeomen~~Yeoman

内容：
作品那里，每个作品负责了什么方面的工作，不要大段描述，分点罗列
1. 负责页面css架构……
2. ...
3. ...
4. ...

**Comment by luxiaojian** [comment]
## 已收到，谢谢！

luhuijian
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

已使用 Sparrow (http://www.sparrowmailapp.com/?sig)  

在 2015年8月25日 星期二，下午6:23，Ivan Zhang 写道：
